### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by Emik234** [Jason1288/prj-rev-bwfs-dasmoto#5]
Summary Grade: Needs Improvement

I did find what I feel are several errors with the website. Some are structural, the others involve accuracy. Your project is missing its CSS file which could've given more style to the site. It's a good idea to leave comments in sections of the code like the ones below to help you or any other person seeing your code be able to get a general overall quick idea of what's correlating with what rather than skimming through the code and having to memorize class names and Id names. It's a good habit to keep up. A good example of this could be done like what I input below this.
```
<!-- EX: Brushes Section -->
<!-- EX: Frames Section -->
<!-- EX: Paint Section -->

```
I suggest working on re-editing this project to nail it this time :-)

**Comment by Jason1288** [comment]
Thank you for the feedback! when you say missing css file, did i only send the html? i added css styles just as the spec sheet suggested. I made a couple changes to the size of the heading because it seemed way to big in the browser window but thats about it. I also didnt clearly understand the folder setup to be honest, but now that you have pointed it out i understand what you mean.
